name: guide_muslim_kids
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^1.0.8

  bloc_concurrency: ^0.3.0
  dartz: ^0.10.1
  device_preview: ^1.3.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  intl: ^0.20.2
  audioplayers: ^6.5.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  flutter_launcher_icons: ^0.14.4

flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  
flutter_assets:
  assets_path:
    - assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: null
  classname: AppImage
  ignore_comments: true
flutter_intl:
  enabled: true