import 'package:flutter/material.dart';

class AppColor {
  AppColor._();
  static const Color scaffoldBackgroundColor = Color(0xFFFFFFFF);
  static const Color cardColor = Color(0xFFFFFFFF);
  static const Color athkarContainTap = Color(0xFFccb992);
  static const Color audioButton = Color(0xFFFFFFFF);
  static const Color namesText = Color(0xFFF6B92C);
  static const Color borderNames = Color(0xFFccb992);
  static const Color secondaryText = Color(0xFFFFFFFF);
  static const Color shadowText = Color(0x73000000);
  static const Color error = Color(0xFFFF5252);
  static const Color titleAboutUs = Color(0xFFFF5722);
  static const Color questionCard = Color(0xFFF6FBFB);
  static const Color lettersBackground = Color(0xFFE0F2F1);
  static const Color lettersBorder = Color(0xFF80CBC4);
  static const Color lettersText1 = Color(0xFF009688);
  static const Color letterButtonBackground = Color(0xFFFFFFFF);
  static const Color correctBorder = Color(0xFF388E3C);
  static const Color incorrectBorder = Color(0xFFD32F2F);
  static const Color correctBackground = Color(0xFFF1F8E9);
  static const Color incorrectBackground = Color(0xFFFFEBEE);
  static const Color dragging = Color(0xFFFFC107);
  static const Color dropZoneFirst = Color(0xFFFF9800);
  static const Color dropZoneBGSakin = Color(0xFFFFF3E0);
  static const Color dropZoneSecond = Color(0xFF2196F3);
  static const Color dropZoneBGMutaharrik = Color(0xFFE3F2FD);
  static const Color shadowLevelItem1 = Color(0xFFD32F2F);
  static const Color bgLevelItem1 = Color(0xFFFF9800);
  static const Color lettersText2 = Color(0xFF3F51B5);
  static const Color lettersBackground2 = Color(0xFFE8EAF6);
  static const Color bgLevelItem2 = Color(0xFF8BC34A);
  static const Color shadowLevelItem2 = Color(0xFF689F38);
  static const Color lettersText3 = Color(0xFF6A1B9A);
  static const Color lettersBackground3 = Color(0xFFF3E5F5);
  static const Color bgLevelItem3 = Color(0xFFFF5722);
  static const Color shadowLevelItem3 = Color(0xFFE64A19);
  static const Color gameBackground = Color(0xFFE0F7FA);
  static const Color lockedStartColor = Color(0xFFBDBDBD);
  static const Color lockedEndColor = Color(0xFF757575);
}
